name: hero
description: Project untuk SF di telkomsel Regional Sumbagsel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.7.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  background_locator: ^1.6.12
  better_player: ^0.0.62
  camera: ^0.9.4+11
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.0.3
  geolocator: ^8.1.1
  google_fonts: any
  google_maps_flutter: ^2.0.1
  intl: ^0.17.0
  loading_animations: ^2.1.0
  location: ^4.1.1
  location_permissions: ^4.0.1
  path: ^1.8.0
#  path_provider: any
  permission_handler: ^8.2.5
  rxdart: ^0.27.3
  screenshot: ^1.2.3
  share: ^2.0.1
  shared_preferences: ^2.0.13
  sqflite: any
  url_launcher: ^6.0.20
  video_player: ^2.2.18
  get_it: ^7.2.0
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  equatable: ^2.0.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter_native_splash:
  image: assets/image/splash512.png
  color: "FFFFFF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/new/ic_hore_apps2.jpg"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/splash512.png
    - assets/image/bgatas.png
    - assets/image/bgbawah.png
    - assets/image/bgmap.png
    - assets/image/logoappbar.png
    - assets/image/textreset.png
    - assets/image/textwelcome.png
    - assets/image/contoh.png
    - assets/image/new/BG.png
    - assets/image/new/big_logo.png
    - assets/image/new/telkomsel.png
    - assets/image/new/ic_hore_apps2.jpg
    - assets/image/coverage/BG.png
    - assets/image/coverage/ic_logo_hore.png
    - assets/image/coverage/logout.png
    - assets/image/icon/en_coverage.png
    - assets/image/icon/en_distri.png
    - assets/image/icon/en_market_audit.png
    - assets/image/icon/en_merch.png
    - assets/image/icon/en_promo.png
    - assets/image/icon/en_clockout.png
    - assets/image/icon/disable/ds_coverage.png
    - assets/image/icon/disable/ds_distri.png
    - assets/image/icon/disable/ds_market_audit.png
    - assets/image/icon/disable/ds_merch.png
    - assets/image/icon/disable/ds_promo.png
    - assets/image/icon/disable/ds_clockout.png
    - assets/image/icon/clockin/enable/ic_en_clock_out.png
    - assets/image/icon/clockin/enable/ic_en_coverage.png
    - assets/image/icon/clockin/enable/ic_en_distribution.png
    - assets/image/icon/clockin/enable/ic_en_market_audit.png
    - assets/image/icon/clockin/enable/ic_en_merchandising.png
    - assets/image/icon/clockin/enable/ic_en_promotion.png
    - assets/image/icon/clockin/complete/ic_ck_clock_out.png
    - assets/image/icon/clockin/complete/ic_ck_coverage.png
    - assets/image/icon/clockin/complete/ic_ck_distribution.png
    - assets/image/icon/clockin/complete/ic_ck_market_audit.png
    - assets/image/icon/clockin/complete/ic_ck_merchandising.png
    - assets/image/icon/clockin/complete/ic_ck_promotion.png
    - assets/image/icon/clockin/disable/ic_ds_clockout.png
    - assets/image/icon/clockin/disable/ic_ds_coverage.png
    - assets/image/icon/clockin/disable/ic_ds_distribution.png
    - assets/image/icon/clockin/disable/ic_ds_merchandising.png
    - assets/image/icon/clockin/disable/ic_ds_promotion.png
    - assets/image/icon/clockin/disable/ic_ds_market_audit.png
    - assets/image/icon/new/ic_coverage.png
    - assets/image/icon/new/ic_distribution.png
    - assets/image/icon/new/ic_market_audit.png
    - assets/image/icon/new/ic_merchandising.png
    - assets/image/icon/new/ic_promotion.png
    - assets/image/icon/new/disable/coverage.png
    - assets/image/icon/new/disable/distribution.png
    - assets/image/icon/new/disable/market_audit.png
    - assets/image/icon/new/disable/merchandising.png
    - assets/image/icon/new/disable/promotion.png
    - assets/image/feature_button/ic_cari_outlet.png
    - assets/image/feature_button/ic_retur.png
    - assets/image/feature_button/ic_tambah_outlet.png
    - assets/image/feature_button/ic_extra_penjualana.png
    - assets/csv/kecamatan.csv
    - assets/csv/kabupaten.csv
    - assets/csv/provinsi.csv
    - assets/csv/kelurahan.csv
    #MT ASSET
    - assets/image/mt/ic_back_chek_menu.png
    - assets/image/mt/ic_tandem_menu.png
    - assets/image/mt/ic_history_sales.png
    - assets/image/mt/ic_history_outlet.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
