name: hero
description: Project untuk SF di telkomsel Regional Sumbagsel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  location: ^4.1.1
  geolocator: ^8.0.1
  share: ^2.0.1
  flutter_launcher_icons: "^0.9.2"
  shared_preferences: ^2.0.9
  intl: ^0.17.0
  rxdart: ^0.27.3
  google_maps_flutter: ^2.0.1
  flutter_native_splash: ^1.0.3
  sqflite: any
  path_provider: any
  better_player: ^0.0.62
  video_player: ^2.0.0
  path: ^1.7.0
  camera: ^0.9.4+3
  loading_animations: "^2.1.0"
  permission_handler: ^8.2.5
  url_launcher: ^6.0.2
  screenshot: ^1.2.3
  background_locator: ^1.5.0+1
  location_permissions: ^4.0.1
#  workmanager: ^0.2.0
#  flutter_local_notifications: ^3.0.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_fonts: any

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  #flutter packages get
  #flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/image/splash512.png
  color: "FFFFFF"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/new/ic_hore_apps2.jpg"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/splash512.png
    - assets/image/bgatas.png
    - assets/image/bgbawah.png
    - assets/image/bgmap.png
    - assets/image/logoappbar.png
    - assets/image/textreset.png
    - assets/image/textwelcome.png
    - assets/image/contoh.png
    - assets/image/new/BG.png
    - assets/image/new/big_logo.png
    - assets/image/new/telkomsel.png
    - assets/image/new/ic_hore_apps2.jpg
    - assets/csv/kecamatan.csv
    - assets/csv/kabupaten.csv
    - assets/csv/provinsi.csv
    - assets/csv/kelurahan.csv

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
